### PR TITLE
Image picker consider movement

### PR DESCRIPTION
**Pull request by marinagmoreira**
Made getting the timestamps a function
Replace option to add timestamps based on time with adding extra timestamps based on remove_low_movement_image tool

### CODE REVIEW

**Review by oleg-alexandrov — COMMENTED** [review]
I trust this was tested. Perhaps the doc needs to be expanded to explain what this new thing does.

**Review by oleg-alexandrov — APPROVED** [review]
Looks good. Not sure about when it comes to adding left bracket first, and the right bracket later. Hope this approach was tested.

**Comment by oleg-alexandrov** [comment]
You can merge this yourself when happy enough on your side. I have no more comments.

**Comment by marinagmoreira** [comment]
> Looks good. Not sure about when it comes to adding left bracket first, and the right bracket later. Hope this approach was tested.

Yeah I tested everything, was useful to have a map with the left bracket and when validated, I fast_merge+bundle_adust the left+right bracket map in.

**Comment by oleg-alexandrov** [comment]
When it comes to the new approach of bracketing in image_picker, based on distance, rather than time, I am a bit concerned it may result in the user picking the bracketing images a bit too far in time from the image they want to bracket.

There is no hard and fast rule here. The key thing to keep in mind is that given a sci cam image, and hoping that the timestamp offset is known accurately, ideally the two closest nav cam images in time are picked to bracket it. Now the code does not aim for that, to give the user some wiggle room if adjusting the timestamp offset manually later. 

Also, note that camera_refiner used to count on the image_picker time bracket, so now that this is changed, the refiner may complain. But likely there's no need to recalibrate any robot by now.

**Comment by marinagmoreira** [comment]
> osest nav cam images in time are picked to bracket it. Now the code does not aim for that, to give the user some wiggle room if adjusting the timestamp offset manually later.

The way the timestamps are chosen for the bracket is unchanged, it's still based on the time, I didn't even edit that code (https://github.com/marinagmoreira/isaac/blame/image_picker_consider_movement/dense_map/geometry_mapper/tools/image_picker.cc#L310).

Where the distance between images was used was to choose extra_sci_cam_timestamps instead of using just a time interval (be aware that this is off by default). This extra timestamp then is processed by the bracketing loop exactly as before. https://github.com/marinagmoreira/isaac/blame/image_picker_consider_movement/dense_map/geometry_mapper/tools/image_picker.cc#L248

**Comment by oleg-alexandrov** [comment]
Marina, thank you for the clarification.

**Pull request merged**
