### PR TITLE
Refactor panorama attitude planner for standalone testing. Port Python reference implementation to C++.

### PR DESCRIPTION
**Pull request by trey0**
This version should have identical inspection manager behavior to the previous version, but it's easier to test the attitude planner on a standalone basis.

I also ported the latest version of the Python reference implementation to C++ so we can compare to the attitude planner that's currently used by the inspection manager.

### CODE REVIEW

**Comment by bcoltin** [comment]
Hi Trey,

I am confused, we already had one working version of this function, and we are adding a second one to do the same thing? Am I missing something? Thanks!

**Comment by trey0** [comment]
> I am confused, we already had one working version of this function, and we are adding a second one to do the same thing? Am I missing something?

Stepping back for a second, part of what I'm trying to do is formalize the semantics of the "panorama coverage planning" problem so that we can agree whether a panorama plan is sound (i.e., covers the area it's supposed to, with required overlap and robustness to pointing error) and within that envelope try to optimize better (reduce execution time by requiring fewer images).

The pano_orientations2() function is a modest improvement in that it accounts for pointing error, is more careful about unnecessary overshoot at the edges of the panorama, and tries to be smarter about not taking too many images near the poles.

I don't regard either version of the function as having been validated thoroughly enough. We never completed and stitched even a single full panorama. I hope to write some tools to visualize coverage to help us get more comfortable with all of this.

**Comment by bcoltin** [comment]
Ok! It sounds like there is more work to do--- I would suggest let's leave this as a pull request and not merge it yet. It would also be better to only have one version to maintain once it's been verified. You and Marina can discuss. Thanks!

**Comment by marinagmoreira** [comment]
closing this one as I used it as base for https://github.com/nasa/isaac/pull/70

**Pull request closed without merging**
